import json

#  initial risk table
def getrisks():
  #x =  '{ "riskid":"John", "age":30, "city":"New York"}'
  #  use this to read json from file but not in heroku
  #  with open('riskjson.json') as f:
  #  return(json.load(f))

   json_string = """
[
{
    "riskid": 1,
    "riskselect": "checked",
    "risktype": "Strategic",
    "riskclassification": "Stakeholders",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "1",
    "risktimeline": "Beginning",
    "risktrigger": "Failure to attend meetings, failure to respond",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Executives fail to support project. The project team may lack the authority to achieve project objectives. In such cases, executive management support is fundamental to project success. When this does not materialize the project fails.",
    "riskcontingency": ""
  },
  {
    "riskid": 2,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "3",
    "riskimpact": "3",
    "riskscore": "5",
    "risktimeline": "Midpoint",
    "risktrigger": "Failure to attend meetings, failure to respond",
    "riskresponse": "Mitigate",
    "riskowner": "Sponsor",
    "riskdescription": "Executives become disengaged with project. Executive management disregards project communications and meetings.",
    "riskcontingency": ""
  },
  {
    "riskid": 3,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Stakeholders",
    "riskprobability": "3",
    "riskimpact": "1",
    "riskscore": "2",
    "risktimeline": "End",
    "risktrigger": "High Change Requests, failure to sign off",
    "riskresponse": "Transfer",
    "riskowner": "Sponsor",
    "riskdescription": "Conflict between executive stakeholders disrupts project.  Members of executive management are combative to the project or there is a disagreement over project issues at the executive level.",
    "riskcontingency": ""
  },
  {
    "riskid": 4,
    "riskselect": "checked",
    "risktype": "Business",
    "riskclassification": "Stakeholders",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "High Change Requests, failure to sign off",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Executive turnover disrupts project.  A key executive leaves the company, the resulting disruption becomes a project issue.",
    "riskcontingency": ""
  },
  {
    "riskid": 5,
    "riskselect": "checked",
    "risktype": "Environmental",
    "riskclassification": "Scope",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "High Change Requests, failure to sign off",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Scope is ill defined.  The general risk of an error or omission in scope definition.",
    "riskcontingency": ""
  },
  {
    "riskid": 6,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Scope",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "High Change Requests, failure to sign off",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Scope creep inflates scope.  Uncontrolled changes and continuous growth of scope.",
    "riskcontingency": ""
  },
  {
    "riskid": 7,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Scope",
    "riskprobability": "3",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints not accepted.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Gold plating inflates scope.  The project team add their own product features that are not in requirements or change requests.",
    "riskcontingency": ""
  },
  {
    "riskid": 8,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Scope",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints not accepted.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Estimates are inaccurate.  Inaccurate estimates is a common project risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 9,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Scope",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints not accepted.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Dependencies are inaccurate. Dependencies dramatically impact the project schedule and costs.",
    "riskcontingency": ""
  },
  {
    "riskid": 11,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Cost",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Earned Value CPI is negative.",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Cost forecasts are inaccurate. Inaccurate cost estimates and forecasts.",
    "riskcontingency": ""
  },
  {
    "riskid": 10,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Scope",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints not accepted.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Activities are missing from scope. Required activities are missing from scope definition.",
    "riskcontingency": ""
  },
  {
    "riskid": 12,
    "riskselect": "checked",
    "risktype": "Market",
    "riskclassification": "Cost",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Exchange rate over time changes more than 2 percent",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Exchange rate variability. When costs are incurred in foreign currencies exchange rates can have a dramatic impact.",
    "riskcontingency": ""
  },
  {
    "riskid": 13,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Change management overload. A large number of change requests dramatically raises the complexity of the project and distracts key resources.",
    "riskcontingency": ""
  },
  {
    "riskid": 14,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Stakeholder conflict over proposed changes. Change requests may be the source of stakeholder conflict.",
    "riskcontingency": ""
  },
  {
    "riskid": 15,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Perceptions that a project failed because of changes.  Large numbers of high priority change requests may lead to the perception that the project has failed. When the schedule and budget are continually extended — stakeholders may feel the project missed its original targets.",
    "riskcontingency": ""
  },
  {
    "riskid": 16,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Lack of a change management system.  Identify any lack of critical tools as a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 17,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "1",
    "risktimeline": "Midpoint",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Lack of a change management process. Change management at the organizational or departmental level is critical to project success. Otherwise, the project will have limited visibility into changes that impact the project.",
    "riskcontingency": "Establish a change control process early in the project."
  },
  {
    "riskid": 18,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "1",
    "risktimeline": "Beginning",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Lack of a change control board. A change control board is essential to managing change for large projects.",
    "riskcontingency": "Establish a change control process early in the project."
  },
  {
    "riskid": 19,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "2",
    "risktimeline": "Beginning",
    "risktrigger": "Changes to Scope.  Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Inaccurate change priorities.  When non-essential changes are prioritized impacting critical schedules.",
    "riskcontingency": "Establish a change control process early in the project."
  },
  {
    "riskid": 20,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "2",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late or not complete.",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Low quality of change requests.  Change requests that are low quality (e.g. ambiguous).",
    "riskcontingency": "TDD Quality Assurance (inspection) of requirements and acceptance criteria in user stories ."
  },
  {
    "riskid": 21,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Change",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Change request conflicts with requirements.  Change requests that make no sense in the context of the requirements.",
    "riskcontingency": ""
  },
  {
    "riskid": 22,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "1",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Stakeholders become disengaged. When stakeholders ignore project communications.",
    "riskcontingency": "Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 23,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "3",
    "riskscore": "2",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Stakeholders have inaccurate expectations. Stakeholders develop inaccurate expectations (believe that the project will achieve something not in the requirements, plan, etc).",
    "riskcontingency": "Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 24,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "1",
    "risktimeline": "Midpoint",
    "risktrigger": "Engagement drops or Changes to Sponsors",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Stakeholder turnover. Stakeholder turnover can lead to project disruptions.",
    "riskcontingency": "Communicate plan to the new stakeholders.  Stakeholder chagnes are processed in project change process"
  },
  {
    "riskid": 25,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Engagement drops or Negative response to project",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Stakeholders fail to support project.  When stakeholders have a negative attitude towards the project and wish to see it fail.",
    "riskcontingency": "Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 26,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Engagement drops or Negative response to project",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Stakeholder conflict.  Disagreement between stakeholders over project issues.",
    "riskcontingency": "Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 27,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Engagement drops or Negative response to project",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Process inputs are low quality. Inputs from stakeholders that are low quality (e.g. business case, requirements, change requests).",
    "riskcontingency": "Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 28,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Communication",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "1",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Project team misunderstand requirements.  When requirements are misinterpreted by the project team a gap develops between expectations, requirements and work packages.",
    "riskcontingency": "TDD Quality Assurance (inspection) of requirements and acceptance criteria in user stories ."
  },
  {
    "riskid": 29,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Communication",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Communication overhead.  When key project resources spend a high percentage of their time engaging stakeholders on project issues and change requests their work may fall behind.",
    "riskcontingency": "TDD Quality Assurance (inspection) of requirements and acceptance criteria in user stories ."
  },
  {
    "riskid": 30,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Communication",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Under communication. Communication is a challenge thats not to be underestimated. You may need to communicate the same idea many times in different ways before people remember it.",
    "riskcontingency": "Update or improve the Communication Plan.  Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 31,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Communication",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Users have inaccurate expectations.  The risk that users believe the project is building an apple when you are really building an orange (i.e. users do not understand the product thats coming their way).",
    "riskcontingency": "Update or improve the Communication Plan.  Determine stakeholder influence and interest early in project"
  },
  {
    "riskid": 32,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Communication",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Impacted individuals are not kept informed. A stakeholder is missing in your communication plan. Anyone who is not informed but is impacted has an excellent reason to throw up project roadblocks. For example, if you build a system but fail to consult the operations group that will be responsible for support.",
    "riskcontingency": "Update or improve the Communication Plan"
  },
  {
    "riskid": 33,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Resource shortfalls. Inability to secure sufficient resources for the project.",
    "riskcontingency": "Review resource plan and budget for resources, extend your search globally "
  },
  {
    "riskid": 34,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Learning curves lead to delays and cost overrun.  When your project team need to acquire new skills for the project theres a risk that productivity will be low.",
    "riskcontingency": "Review resource plan and budget for resources, extend your search globally with skilled resources"
  },
  {
    "riskid": 35,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints not accepted, Sprints are late, Quality of deliverables is low.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Training is not available.  Quality training for certain skills can be difficult to secure.",
    "riskcontingency": "Review resource plan and budget for resources, extend your search globally with skilled resources for training. "
  },
  {
    "riskid": 36,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints not accepted, Sprints are late, Quality of deliverables is low.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Training is inadequate.  Training is often a poor substitute for professional experience. Projects should not assume that resources will be fully productive in a new skill.",
    "riskcontingency": "Review resource plan and budget for resources, extend your search globally with skilled resources for training. "
  },
  {
    "riskid": 37,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late, Quality of deliverables is low.",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Resources are inexperienced.  Resources who are just out of school or who are new to your industry or profession tend to make more mistakes and be less productive.",
    "riskcontingency": "Review resource plan and budget for resources, extend your search globally with skilled resources for training. "
  },
  {
    "riskid": 38,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late, Quality of deliverables is low.",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Resource performance issues. Resources who perform below expectations.",
    "riskcontingency": "Review resource plan.  Coaching or replace resources."
  },
  {
    "riskid": 39,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Negative sentiment score or negative sentiment slope",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Team members with negative attitudes towards the project.  Resources who are negative towards the project may actively or passively sabotage project efforts.",
    "riskcontingency": "Review resource plan.  Coaching or replace resources."
  },
  {
    "riskid": 40,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Engagement. Changes to team.",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Resource turnover.  Resource turnover leads to delays and cost overrun.",
    "riskcontingency": "Resource planning.   Plan for changes in key resources at start of project.  Ensure onboarding activites and documentation is up to date to ensure efficient transition. "
  },
  {
    "riskid": 41,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Negative sentiment score or negative sentiment slope",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Low team motivation.  Your team lacks motivation. This is a particularly common risk for long running projects.",
    "riskcontingency": "Review resource plan.  Coaching or replace resources."
  },
  {
    "riskid": 42,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Engagement, low engagement.  Negative sentiment score",
    "riskresponse": "Mitigate",
    "riskowner": "ProjectManager",
    "riskdescription": "Lack of commitment from functional managers.  In a matrix organization your team may report to functional managers. These functional managers are important stakeholders whose support is critical.",
    "riskcontingency": "Update or improve the Communication Plan.  Determine functional manager influence and interest early in project"
  },
  {
    "riskid": 43,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Architecture fails to pass governance processes.  Plan for any architectural or technology governance processes that the project may need to pass.",
    "riskcontingency": ""
  },
  {
    "riskid": 44,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Architecture lacks flexibility. The architecture is incapable of supporting change requests and needs to be reworked.",
    "riskcontingency": "Rework Architecture.  Increase expert inspections and architecture reviews."
  },
  {
    "riskid": 45,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Architecture is not fit for purpose.  The architecture is low quality.",
    "riskcontingency": "Rework Architecture.  Increase expert inspections and architecture reviews."
  },
  {
    "riskid": 46,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Architecture is infeasible.  The architecture is impossible to implement, excessively costly or does not support the requirements.",
    "riskcontingency": "Quality Assurance Planning.  Increase expert inspections and four eyes"
  },
  {
    "riskid": 47,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Design is infeasible.  The design is not possible, is excessively costly or does not support the requirements.",
    "riskcontingency": "Quality Assurance Planning.  TDD Test driven development, increase inspections"
  },
  {
    "riskid": 48,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Design lacks flexibility.  A poor design makes change requests difficult and costly.",
    "riskcontingency": "Quality Assurance Planning.  TDD Test driven development, increase inspections"
  },
  {
    "riskid": 49,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Design is not fit for purpose. The design is low quality.",
    "riskcontingency": "Quality Assurance Planning.  TDD Test driven development, increase inspections"
  },
  {
    "riskid": 50,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Midpoint",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Design fails peer review.  It is a good idea to have peers or architectural experts review your designs.",
    "riskcontingency": "Quality Assurance Planning.  TDD Test driven development, increase inspections"
  },
  {
    "riskid": 51,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not fit for purpose. Technology components are low quality.",
    "riskcontingency": "Quality Assurance Planning.  TDD Test driven development, increase inspections"
  },
  {
    "riskid": 52,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not scalable.  Components that cannot be scaled to meet performance demands.",
    "riskcontingency": "Quality Assurance Planning.  Performance planning and testing"
  },
  {
    "riskid": 53,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Earned Value, SPI Schedule Performance is negative",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not interoperable.  Components that lack standard interfaces.",
    "riskcontingency": ""
  },
  {
    "riskid": 54,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not compliant with standards and best practices.  Non-standard components that violate best practices.",
    "riskcontingency": ""
  },
  {
    "riskid": 55,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Security Alerts",
    "riskresponse": "Mitigate",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components have security vulnerabilities. Security vulnerabilities are key technology risks.",
    "riskcontingency": "Quality Assurance Planning.  Automated scanning and inspection"
  },
  {
    "riskid": 56,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late, Earned value CPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are over-engineered.  A component thats bloated with unneeded functionality and design features.",
    "riskcontingency": ""
  },
  {
    "riskid": 57,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components lack stability.  Components that crash.",
    "riskcontingency": "Quality Assurance Planning,  Rework architecture"
  },
  {
    "riskid": 58,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not extensible. Components that are difficult to extend with new capabilities.",
    "riskcontingency": ""
  },
  {
    "riskid": 59,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technology components are not reliable. Components that fail after a short time.",
    "riskcontingency": ""
  },
  {
    "riskid": 60,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "ProjectManager",
    "riskdescription": "Information security incidents. The risk of a a security incident during the project (e.g. information is leaked).",
    "riskcontingency": ""
  },
  {
    "riskid": 61,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "ProjectManager",
    "riskdescription": "System outages. Critical systems such as your test environments go down.",
    "riskcontingency": ""
  },
  {
    "riskid": 62,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "AgileTeam",
    "riskdescription": "Legacy components lack documentation. Integration with undocumented legacy components is a high risk activity.",
    "riskcontingency": "Requirements Planning. Refactor and document legacy code and integrations "
  },
  {
    "riskid": 63,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Earned Value:  CPI is negative",
    "riskresponse": "Accept",
    "riskowner": "ProductOwner",
    "riskdescription": "Legacy components are out of support.  Integration with legacy components that are no longer in support.",
    "riskcontingency": ""
  },
  {
    "riskid": 64,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "Cost to maintain is high, frequent and lengthy outages",
    "riskresponse": "Accept",
    "riskowner": "Operations",
    "riskdescription": "Components or products are not maintainable.  Technology components, tools or platforms that are difficult to maintain (e.g. lacking documentation, rare skills, complex or experimental).",
    "riskcontingency": ""
  },
  {
    "riskid": 65,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "Cost to maintain is high, frequent and lengthy outages",
    "riskresponse": "Avoid",
    "riskowner": "Operations",
    "riskdescription": "Components or products cannot be operationalized.  Technology operations may have criteria for operationalization of new systems that need to be met.",
    "riskcontingency": ""
  },
  {
    "riskid": 66,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not complete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Project management tool problems & issues.  Technical problems with the project management tools themselves.",
    "riskcontingency": ""
  },
  {
    "riskid": 67,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not complete",
    "riskresponse": "Accept",
    "riskowner": "Operations",
    "riskdescription": "Delays to required infrastructure.  Delays to infrastructure such as hardware or software.",
    "riskcontingency": ""
  },
  {
    "riskid": 68,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Failure to integrate with business processes. The risk that your product will fail to fit into the existing business.",
    "riskcontingency": ""
  },
  {
    "riskid": 69,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not complete",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Failure to integrate with systems. The risk that your product will fail to integrate with existing systems.",
    "riskcontingency": ""
  },
  {
    "riskid": 70,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or not complete",
    "riskresponse": "Avoid",
    "riskowner": "Operations",
    "riskdescription": "Integration testing environments are not available. The risk that environments wont be available to test integration.",
    "riskcontingency": ""
  },
  {
    "riskid": 71,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Failure to integration with the organization. The risk that your project fails to integrate with the organization. This happens when the project is focused on delivering something specific and fails to look at the organization as a whole. For example, you deliver a sales system but your organization does not have a sales team.",
    "riskcontingency": ""
  },
  {
    "riskid": 72,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Failure to integrate components. The risk that product components will fail to integrate with each other. This can represent a significant risk when youve outsourced work to a large number of vendors.",
    "riskcontingency": ""
  },
  {
    "riskid": 73,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Project disrupts operations. The last thing you want is for your project to disrupt business operations and damage the firms financial results. Think about risks beyond project failure.",
    "riskcontingency": ""
  },
  {
    "riskid": 74,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Project disrupts sales. The risk that the project disrupts sales effectiveness.",
    "riskcontingency": ""
  },
  {
    "riskid": 75,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Project disrupts compliance. The risk that the project disrupts compliance processes such as audits and reporting.",
    "riskcontingency": ""
  },
  {
    "riskid": 76,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements fail to align with strategy. Your requirements conflict with the firms strategy. If you sense that this is the case, list it as a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 77,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements fail to align with business processes. The requirements make no sense in the context of the business.",
    "riskcontingency": ""
  },
  {
    "riskid": 78,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements fail to align with systems. The requirements fail to align with other systems (e.g. they duplicate functionality).",
    "riskcontingency": ""
  },
  {
    "riskid": 79,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements have compliance issues. If you have any doubt that requirements comply with the law list it as a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 80,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements are ambiguous. Requirements are unclear and open to interpretation.",
    "riskcontingency": ""
  },
  {
    "riskid": 81,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements are low quality. Requirements are not fit for purpose.",
    "riskcontingency": ""
  },
  {
    "riskid": 82,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "1",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints not accepted, Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Requirements are incomplete.  You can spot obvious holes in the requirements.",
    "riskcontingency": ""
  },
  {
    "riskid": 83,
    "riskselect": "checked",
    "risktype": "Decisions",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Decision delays impact project.  Establish guidelines for decision turnaround time. Identify the risk that guidelines will be exceeded.",
    "riskcontingency": "Communication planning improvement "
  },
  {
    "riskid": 84,
    "riskselect": "checked",
    "risktype": "Decisions",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Decisions are ambiguous.  Stakeholders may have a tendency to make decisions that are intentionally ambiguous (a responsibility avoidance technique). This can be identified as a risk and managed.",
    "riskcontingency": ""
  },
  {
    "riskid": 85,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late. Sprints incomplete",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Decisions are low quality.  Decisions are not fit for purpose.",
    "riskcontingency": ""
  },
  {
    "riskid": 86,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Project",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late. Sprints not accepted",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Decisions are incomplete. Issue resolutions that do not address the issue or create more issues.",
    "riskcontingency": ""
  },
  {
    "riskid": 87,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "No response to RFP. The risk that there is limited response to an RFP. This occurs when the RFP terms are unacceptable to vendors or if your firm has a bad reputation amongst vendors.",
    "riskcontingency": ""
  },
  {
    "riskid": 88,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Low quality responses to RFP. Half hearted responses to your RFP that are unusable.",
    "riskcontingency": ""
  },
  {
    "riskid": 89,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Failure to negotiation a reasonable price for contracts.  Inability to negotiate a reasonable price for contracts. This occurs when the requirements or contract terms make vendors nervous.",
    "riskcontingency": ""
  },
  {
    "riskid": 90,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Unacceptable contract terms. Inability to negotiate acceptable contract terms.",
    "riskcontingency": ""
  },
  {
    "riskid": 91,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or incomplete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Conflict with vendor leads to project issues. The relationship with vendor turns to conflict and project issues mount.",
    "riskcontingency": ""
  },
  {
    "riskid": 92,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late or incomplete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Conflict between vendors leads to project issues.  Your vendors develop conflict with each other and cooperation breaks down.",
    "riskcontingency": ""
  },
  {
    "riskid": 93,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Sprints are late or incomplete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Vendors start late. The risk of a late start.",
    "riskcontingency": ""
  },
  {
    "riskid": 94,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late or incomplete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Vendor components fail to meet requirements. A vendor misunderstands requirements or delivers components that are completely off the mark.",
    "riskcontingency": ""
  },
  {
    "riskid": 95,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints not accepted, Sprints are late or incomplete",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Vendor components are low quality.  Vendor components are not fit for purpose.",
    "riskcontingency": ""
  },
  {
    "riskid": 96,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late",
    "riskresponse": "Avoid",
    "riskowner": "Operations",
    "riskdescription": "Infrastructure is low quality. Your infrastructure fails or is not fit for purpose.",
    "riskcontingency": ""
  },
  {
    "riskid": 97,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Sprints are late, Earned Value SPI is negative",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Service quality is low.  Services you procure such as consulting are not fit for purpose.",
    "riskcontingency": ""
  },
  {
    "riskid": 98,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Procurement",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Vendor components introduce third party liability.  Vendor components introduce liability (e.g. they violate patents).",
    "riskcontingency": ""
  },
  {
    "riskid": 99,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Requirements",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Loss of intellectual property.  Vendors spy on you.",
    "riskcontingency": ""
  },
  {
    "riskid": 100,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "SPI negative",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Project team lack authority to complete work. If you lack specific authorities required to deliver the project list this as a risk.",
    "riskcontingency": "Project Planning.  Clarify roles, responsibilities using RACI chart"
  },
  {
    "riskid": 101,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Authority is unclear. It is unclear who has the authority to accomplish a project objective.",
    "riskcontingency": "Project Planning.  Clarify roles, responsibilities using RACI chart"
  },
  {
    "riskid": 102,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "CPI",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Delays to stakeholder approvals impact the project. The risk that approval deadlines will be exceeded.",
    "riskcontingency": "Review Communication Plan and Stakeholder management plan. "
  },
  {
    "riskid": 103,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "CPI",
    "riskresponse": "Avoid",
    "riskowner": "Sponsor",
    "riskdescription": "Delays to financial approvals impact the project.  The risk of delays to financial approvals and processes to release funds.",
    "riskcontingency": "Review Communication Plan and Stakeholder management plan. "
  },
  {
    "riskid": 104,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Schedule Performance Index is negative",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Delays to procurement processes impact the project.  Many organizations have specific procurement processes that must be followed. These processes can be time consuming and highly variable. Document the risk that procurement process will exceed deadlines.",
    "riskcontingency": "Project Planning and Communication, plan for sponsor procurement process"
  },
  {
    "riskid": 105,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Schedule Performance Index is negative",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Delays to recruiting processes impact the project.  If your project involves recruiting resources, this will typically take many months and is highly variable.",
    "riskcontingency": "Resource Planning"
  },
  {
    "riskid": 106,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "Schedule Performance Index is negative",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Delays to training impact the project.  If your training budget requires separate approvals (e.g. from functional managers or HR) document the risk that this will be slow.",
    "riskcontingency": "Resource planning. "
  },
  {
    "riskid": 107,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Stakeholders",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "Sprints not accepted",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "The project fails to match the organizations culture.  A culture fit issue between your product and the organization. If the organizations culture calls for employees to bring their own mobile devices to work (BYOD) and you build a user interface that only works on a specific device.",
    "riskcontingency": "Stakeholder Management Plan"
  },
  {
    "riskid": 108,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Engagement",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "An organizational restructuring throws the project into chaos.  If your project has a large footprint it may be extremely sensitive to organizational changes.",
    "riskcontingency": "Resource Planning "
  },
  {
    "riskid": 109,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Resources",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "Engagement",
    "riskresponse": "Transfer",
    "riskowner": "Sponsor",
    "riskdescription": "A merger or acquisition disrupts the project. Mergers & acquisitions may represent significant organizational changes.",
    "riskcontingency": "Resource Planning, Communication Plans"
  },
  {
    "riskid": 110,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "External",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Legal & regulatory change impacts project.  If your project spans areas that are compliance-sensitive you may want to list regulatory change as a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 111,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Project",
    "riskprobability": "1",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "External",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Force Majeure (e.g. act of nature) impacts project.  Major disruptions such as acts of nature.",
    "riskcontingency": ""
  },
  {
    "riskid": 112,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "External",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Market forces impact project.  Market changes impact project (e.g. a market crash).",
    "riskcontingency": ""
  },
  {
    "riskid": 113,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "External",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Technical change impacts project. A technology innovation changes your industry and impacts the project.",
    "riskcontingency": ""
  },
  {
    "riskid": 114,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "ProductOwner",
    "riskdescription": "Business change impacts project. A business innovation changes your industry and impacts the project.",
    "riskcontingency": ""
  },
  {
    "riskid": 115,
    "riskselect": "checked",
    "risktype": "Process",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Failure to follow methodology. If your organization asks you to streamline your project management methodology, that can be documented as a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 116,
    "riskselect": "checked",
    "risktype": "Process",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Lack of management or control.  A lack of project management should be documented as a risk. For example, if resource constraints cause the project to skip certain project management best practices.",
    "riskcontingency": ""
  },
  {
    "riskid": 117,
    "riskselect": "checked",
    "risktype": "Process",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "ProjectManager",
    "riskdescription": "Errors in key project management processes Errors in project management such as schedule errors.",
    "riskcontingency": ""
  },
  {
    "riskid": 118,
    "riskselect": "checked",
    "risktype": "Process",
    "riskclassification": "Project",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Accept",
    "riskowner": "Sponsor",
    "riskdescription": "Counterparty risk. The risk you get back when you transfer a risk.",
    "riskcontingency": ""
  },
  {
    "riskid": 119,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Users reject the prototype.  One of the key methods of improving user acceptance is to get regular prototypes in front of users. There is always a risk that these prototypes will be rejected (require significant rework).",
    "riskcontingency": "Decrease sprint cadence.  Get prototypes in front of users sooner to avoid doing work that is not what they want."
  },
  {
    "riskid": 120,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "1",
    "riskimpact": "2",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "User interface does not allow users to complete tasks The risk that the user interface does not allow users to complete end-to-end tasks.",
    "riskcontingency": ""
  },
  {
    "riskid": 121,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "3",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "User interface is low quality. The user interface is buggy, slow or difficult to use.",
    "riskcontingency": ""
  },
  {
    "riskid": 122,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "User interface is not accessible.  In many jurisdictions, user interfaces must be accessible (e.g. employment or consumer law). Many organizational cultures require accessible user interfaces.",
    "riskcontingency": "Review Quality Assurance Plan"
  },
  {
    "riskid": 123,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "SPI",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Project reduces business productivity.  Users identify your product(s) as reducing their productivity.",
    "riskcontingency": ""
  },
  {
    "riskid": 124,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Technology",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Project reduces innovation.  Users identify your product(s) as a roadblock to innovation.",
    "riskcontingency": ""
  },
  {
    "riskid": 125,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Beginning",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Product disrupts business metrics (measurements of objectives). Your product launch causes business KPIs to worsen. For example, if you launch a new ERP and Supply Chain Cycle Times jump.",
    "riskcontingency": ""
  },
  {
    "riskid": 126,
    "riskselect": "checked",
    "risktype": "Product",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Users reject the product. The general risk that users will reject your product.",
    "riskcontingency": ""
  },
  {
    "riskid": 127,
    "riskselect": "checked",
    "risktype": "Operations",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Product does not sell. Demand risk for the new product.",
    "riskcontingency": ""
  },
  {
    "riskid": 128,
    "riskselect": "checked",
    "risktype": "Project",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "Any",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "AgileTeam",
    "riskdescription": "Product incurs legal liability. The product has quality issues that harm your customers.",
    "riskcontingency": ""
  },
  {
    "riskid": 129,
    "riskselect": "checked",
    "risktype": "Product",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Product negatively affects brand. The product has quality issues that damage your brand.",
    "riskcontingency": ""
  },
  {
    "riskid": 130,
    "riskselect": "checked",
    "risktype": "Product",
    "riskclassification": "Requirements",
    "riskprobability": "2",
    "riskimpact": "1",
    "riskscore": "3",
    "risktimeline": "End",
    "risktrigger": "",
    "riskresponse": "Avoid",
    "riskowner": "ProductOwner",
    "riskdescription": "Product negatively affects reputation. The product generates negative publicity and/or damages customer relationships.",
    "riskcontingency": ""
  }
]
"""
   return(json.loads(json_string))
