[theme]
primaryColor="#264653"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F4A261"
textColor="#2A9D8F"
font="sans serif"

[global]
dataFrameSerialization = "legacy"
disableWidgetStateDuplicationWarning = true

